/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/symbols": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Configured symbols and the health of each exchange feed */
        get: operations["listSymbols"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest closed window for a symbol */
        get: operations["getLatestMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/{symbol}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent windows kept in memory by the gateway (oldest first) */
        get: operations["getMetricsHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Alert history, newest first
         * @description With `symbol`, results can be paged with `cursor` (use `next_cursor`
         *     from the previous page). Without `symbol`, the newest alerts of all
         *     symbols are merged and paging is not available.
         */
        get: operations["listAlerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** IDs of stored backtest runs */
        get: operations["listBacktests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backtests/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A backtest report (the report.json written by the backtester) */
        get: operations["getBacktest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Process is running */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ready to serve */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Starting up */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prometheus metrics */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Prometheus text format */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ExchangeStats: {
            exchange: string;
            vwap: string;
            volume: string;
            trade_count: number;
            /** Format: int64 */
            last_trade_ns: number;
        };
        Metrics: {
            symbol: string;
            /** @enum {integer} */
            window_secs: 1 | 10 | 60;
            /** Format: int64 */
            window_start_ns: number;
            /** Format: int64 */
            window_end_ns: number;
            /** @description Volume-weighted average price */
            vwap: string;
            volume: string;
            trade_count: number;
            /** @description Annualised volatility of the window (1.0 = 100%) */
            realised_vol: number;
            high: string;
            low: string;
            last_price: string;
            /** @description Coinbase VWAP minus Kraken VWAP, in basis points */
            xex_spread_bps: number;
            /** Format: int64 */
            emitted_at_ns: number;
            exchanges: components["schemas"]["ExchangeStats"][];
        };
        Alert: {
            symbol: string;
            alert_id: string;
            rule_name: string;
            /** @enum {string} */
            severity: "INFO" | "WARN" | "CRITICAL";
            /** Format: int64 */
            window_end_ns: number;
            /** @description Set for per-exchange rules such as stale_feed */
            exchange?: string;
            message: string;
            values: {
                [key: string]: number;
            };
        };
        AlertPage: {
            items: components["schemas"]["Alert"][];
            next_cursor?: string;
        };
        FeedHealth: {
            exchange: string;
            symbol: string;
            /** Format: int64 */
            last_trade_ns: number;
            reconnects: number;
            /** @enum {string} */
            status: "connected" | "reconnecting" | "stale" | "unknown";
            /** Format: int64 */
            reported_at_ns: number;
        };
        SymbolInfo: {
            symbol: string;
            feeds: components["schemas"]["FeedHealth"][];
        };
    };
    responses: {
        /** @description Error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error: string;
                };
            };
        };
    };
    parameters: {
        Symbol: string;
        /** @description Window size in seconds. */
        Window: 1 | 10 | 60;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listSymbols: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SymbolInfo"][];
                };
            };
        };
    };
    getLatestMetrics: {
        parameters: {
            query?: {
                /** @description Window size in seconds. */
                window?: components["parameters"]["Window"];
            };
            header?: never;
            path: {
                symbol: components["parameters"]["Symbol"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Metrics"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    getMetricsHistory: {
        parameters: {
            query?: {
                /** @description Window size in seconds. */
                window?: components["parameters"]["Window"];
                limit?: number;
            };
            header?: never;
            path: {
                symbol: components["parameters"]["Symbol"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Metrics"][];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    listAlerts: {
        parameters: {
            query?: {
                symbol?: string;
                /** @description Only alerts for windows ending at or after this time (ns). */
                since?: number;
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertPage"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    listBacktests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        runs: string[];
                    };
                };
            };
        };
    };
    getBacktest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            404: components["responses"]["Error"];
        };
    };
}
