// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: tickstream/v1/tickstream.proto

package domain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Side int32

const (
	Side_SIDE_UNSPECIFIED Side = 0
	Side_SIDE_BUY         Side = 1
	Side_SIDE_SELL        Side = 2
)

// Enum value maps for Side.
var (
	Side_name = map[int32]string{
		0: "SIDE_UNSPECIFIED",
		1: "SIDE_BUY",
		2: "SIDE_SELL",
	}
	Side_value = map[string]int32{
		"SIDE_UNSPECIFIED": 0,
		"SIDE_BUY":         1,
		"SIDE_SELL":        2,
	}
)

func (x Side) Enum() *Side {
	p := new(Side)
	*p = x
	return p
}

func (x Side) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Side) Descriptor() protoreflect.EnumDescriptor {
	return file_tickstream_v1_tickstream_proto_enumTypes[0].Descriptor()
}

func (Side) Type() protoreflect.EnumType {
	return &file_tickstream_v1_tickstream_proto_enumTypes[0]
}

func (x Side) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Side.Descriptor instead.
func (Side) EnumDescriptor() ([]byte, []int) {
	return file_tickstream_v1_tickstream_proto_rawDescGZIP(), []int{0}
}

type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_INFO                 Severity = 1
	Severity_WARN                 Severity = 2
	Severity_CRITICAL             Severity = 3
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "INFO",
		2: "WARN",
		3: "CRITICAL",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"INFO":                 1,
		"WARN":                 2,
		"CRITICAL":             3,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_tickstream_v1_tickstream_proto_enumTypes[1].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_tickstream_v1_tickstream_proto_enumTypes[1]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_tickstream_v1_tickstream_proto_rawDescGZIP(), []int{1}
}

type FeedStatus int32

const (
	FeedStatus_FEED_STATUS_UNSPECIFIED  FeedStatus = 0
	FeedStatus_FEED_STATUS_CONNECTED    FeedStatus = 1
	FeedStatus_FEED_STATUS_RECONNECTING FeedStatus = 2
	FeedStatus_FEED_STATUS_STALE        FeedStatus = 3
)

// Enum value maps for FeedStatus.
var (
	FeedStatus_name = map[int32]string{
		0: "FEED_STATUS_UNSPECIFIED",
		1: "FEED_STATUS_CONNECTED",
		2: "FEED_STATUS_RECONNECTING",
		3: "FEED_STATUS_STALE",
	}
	FeedStatus_value = map[string]int32{
		"FEED_STATUS_UNSPECIFIED":  0,
		"FEED_STATUS_CONNECTED":    1,
		"FEED_STATUS_RECONNECTING": 2,
		"FEED_STATUS_STALE":        3,
	}
)

func (x FeedStatus) Enum() *FeedStatus {
	p := new(FeedStatus)
	*p = x
	return p
}

func (x FeedStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FeedStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_tickstream_v1_tickstream_proto_enumTypes[2].Descriptor()
}

func (FeedStatus) Type() protoreflect.EnumType {
	return &file_tickstream_v1_tickstream_proto_enumTypes[2]
}

func (x FeedStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FeedStatus.Descriptor instead.
func (FeedStatus) EnumDescriptor() ([]byte, []int) {
	return file_tickstream_v1_tickstream_proto_rawDescGZIP(), []int{2}
}

// Trade is the canonical, exchange-agnostic trade record published to md.trades.
type Trade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      string                 `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`                             // "coinbase" | "kraken"
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`                                 // canonical, e.g. "BTC-USD"
	TradeId       string                 `protobuf:"bytes,3,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`                // exchange-native ID
	EventTimeNs   int64                  `protobuf:"varint,4,opt,name=event_time_ns,json=eventTimeNs,proto3" json:"event_time_ns,omitempty"` // exchange timestamp, UTC
	RecvTimeNs    int64                  `protobuf:"varint,5,opt,name=recv_time_ns,json=recvTimeNs,proto3" json:"recv_time_ns,omitempty"`    // when the ingestor received it
	Price         string                 `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`                                   // decimal string: never float for prices
	Size          string                 `protobuf:"bytes,7,opt,name=size,proto3" json:"size,omitempty"`
	Side          Side                   `protobuf:"varint,8,opt,name=side,proto3,enum=tickstream.v1.Side" json:"side,omitempty"` // aggressor (taker) side
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trade) Reset() {
	*x = Trade{}
	mi := &file_tickstream_v1_tickstream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_tickstream_v1_tickstream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_tickstream_v1_tickstream_proto_rawDescGZIP(), []int{0}
}

func (x *Trade) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *Trade) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Trade) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

func (x *Trade) GetEventTimeNs() int64 {
	if x != nil {
		return x.EventTimeNs
	}
	return 0
}

func (x *Trade) GetRecvTimeNs() int64 {
	if x != nil {
		return x.RecvTimeNs
	}
	return 0
}

func (x *Trade) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Trade) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *Trade) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_SIDE_UNSPECIFIED
}

// ExchangeStats is the per-exchange breakdown of a symbol window.
type ExchangeStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      string                 `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Vwap          string                 `protobuf:"bytes,2,opt,name=vwap,proto3" json:"vwap,omitempty"`
	Volume        string                 `protobuf:"bytes,3,opt,name=volume,proto3" json:"volume,omitempty"`
	TradeCount    int64                  `protobuf:"varint,4,opt,name=trade_count,json=tradeCount,proto3" json:"trade_count,omitempty"`
	LastTradeNs   int64                  `protobuf:"varint,5,opt,name=last_trade_ns,json=lastTradeNs,proto3" json:"last_trade_ns,omitempty"` // event time of the last trade from this exchange in the window
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeStats) Reset() {
	*x = ExchangeStats{}
	mi := &file_tickstream_v1_tickstream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeStats) ProtoMessage() {}

func (x *ExchangeStats) ProtoReflect() protoreflect.Message {
	mi := &file_tickstream_v1_tickstream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeStats.ProtoReflect.Descriptor instead.
func (*ExchangeStats) Descriptor() ([]byte, []int) {
	return file_tickstream_v1_tickstream_proto_rawDescGZIP(), []int{1}
}

func (x *ExchangeStats) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *ExchangeStats) GetVwap() string {
	if x != nil {
		return x.Vwap
	}
	return ""
}

func (x *ExchangeStats) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *ExchangeStats) GetTradeCount() int64 {
	if x != nil {
		return x.TradeCount
	}
	return 0
}

func (x *ExchangeStats) GetLastTradeNs() int64 {
	if x != nil {
		return x.LastTradeNs
	}
	return 0
}

// Metrics is one record per symbol per closed window, published to md.metrics.
type Metrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	WindowStartNs int64                  `protobuf:"varint,2,opt,name=window_start_ns,json=windowStartNs,proto3" json:"window_start_ns,omitempty"`
	WindowEndNs   int64                  `protobuf:"varint,3,opt,name=window_end_ns,json=windowEndNs,proto3" json:"window_end_ns,omitempty"`
	WindowSecs    int32                  `protobuf:"varint,4,opt,name=window_secs,json=windowSecs,proto3" json:"window_secs,omitempty"` // 1, 10, 60
	Vwap          string                 `protobuf:"bytes,5,opt,name=vwap,proto3" json:"vwap,omitempty"`
	Volume        string                 `protobuf:"bytes,6,opt,name=volume,proto3" json:"volume,omitempty"`
	TradeCount    int64                  `protobuf:"varint,7,opt,name=trade_count,json=tradeCount,proto3" json:"trade_count,omitempty"`
	RealisedVol   float64                `protobuf:"fixed64,8,opt,name=realised_vol,json=realisedVol,proto3" json:"realised_vol,omitempty"` // annualised, from log returns
	High          string                 `protobuf:"bytes,9,opt,name=high,proto3" json:"high,omitempty"`
	Low           string                 `protobuf:"bytes,10,opt,name=low,proto3" json:"low,omitempty"`
	XexSpreadBps  float64                `protobuf:"fixed64,11,opt,name=xex_spread_bps,json=xexSpreadBps,proto3" json:"xex_spread_bps,omitempty"` // cross-exchange divergence
	EmittedAtNs   int64                  `protobuf:"varint,12,opt,name=emitted_at_ns,json=emittedAtNs,proto3" json:"emitted_at_ns,omitempty"`
	LastPrice     string                 `protobuf:"bytes,13,opt,name=last_price,json=lastPrice,proto3" json:"last_price,omitempty"` // price of the last trade (by event time) in the window
	Exchanges     []*ExchangeStats       `protobuf:"bytes,14,rep,name=exchanges,proto3" json:"exchanges,omitempty"`                  // sorted by exchange name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_tickstream_v1_tickstream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_tickstream_v1_tickstream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_tickstream_v1_tickstream_proto_rawDescGZIP(), []int{2}
}

func (x *Metrics) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Metrics) GetWindowStartNs() int64 {
	if x != nil {
		return x.WindowStartNs
	}
	return 0
}

func (x *Metrics) GetWindowEndNs() int64 {
	if x != nil {
		return x.WindowEndNs
	}
	return 0
}

func (x *Metrics) GetWindowSecs() int32 {
	if x != nil {
		return x.WindowSecs
	}
	return 0
}

func (x *Metrics) GetVwap() string {
	if x != nil {
		return x.Vwap
	}
	return ""
}

func (x *Metrics) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *Metrics) GetTradeCount() int64 {
	if x != nil {
		return x.TradeCount
	}
	return 0
}

func (x *Metrics) GetRealisedVol() float64 {
	if x != nil {
		return x.RealisedVol
	}
	return 0
}

func (x *Metrics) GetHigh() string {
	if x != nil {
		return x.High
	}
	return ""
}

func (x *Metrics) GetLow() string {
	if x != nil {
		return x.Low
	}
	return ""
}

func (x *Metrics) GetXexSpreadBps() float64 {
	if x != nil {
		return x.XexSpreadBps
	}
	return 0
}

func (x *Metrics) GetEmittedAtNs() int64 {
	if x != nil {
		return x.EmittedAtNs
	}
	return 0
}

func (x *Metrics) GetLastPrice() string {
	if x != nil {
		return x.LastPrice
	}
	return ""
}

func (x *Metrics) GetExchanges() []*ExchangeStats {
	if x != nil {
		return x.Exchanges
	}
	return nil
}

type Alert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertId       string                 `protobuf:"bytes,1,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"` // deterministic hash(rule, symbol, window_end[, exchange])
	RuleName      string                 `protobuf:"bytes,2,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Severity      Severity               `protobuf:"varint,4,opt,name=severity,proto3,enum=tickstream.v1.Severity" json:"severity,omitempty"`
	WindowEndNs   int64                  `protobuf:"varint,5,opt,name=window_end_ns,json=windowEndNs,proto3" json:"window_end_ns,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Values        map[string]float64     `protobuf:"bytes,7,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Exchange      string                 `protobuf:"bytes,8,opt,name=exchange,proto3" json:"exchange,omitempty"` // set for per-exchange rules (stale_feed, feed_gap)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_tickstream_v1_tickstream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_tickstream_v1_tickstream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_tickstream_v1_tickstream_proto_rawDescGZIP(), []int{3}
}

func (x *Alert) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

func (x *Alert) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *Alert) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Alert) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *Alert) GetWindowEndNs() int64 {
	if x != nil {
		return x.WindowEndNs
	}
	return 0
}

func (x *Alert) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Alert) GetValues() map[string]float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *Alert) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

// FeedHealth is published periodically by the ingestor to md.feed_health.
type FeedHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      string                 `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	LastTradeNs   int64                  `protobuf:"varint,3,opt,name=last_trade_ns,json=lastTradeNs,proto3" json:"last_trade_ns,omitempty"` // receive time of the last trade seen for this symbol
	Reconnects    int64                  `protobuf:"varint,4,opt,name=reconnects,proto3" json:"reconnects,omitempty"`                        // reconnects since ingestor start
	Status        FeedStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=tickstream.v1.FeedStatus" json:"status,omitempty"`
	ReportedAtNs  int64                  `protobuf:"varint,6,opt,name=reported_at_ns,json=reportedAtNs,proto3" json:"reported_at_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedHealth) Reset() {
	*x = FeedHealth{}
	mi := &file_tickstream_v1_tickstream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedHealth) ProtoMessage() {}

func (x *FeedHealth) ProtoReflect() protoreflect.Message {
	mi := &file_tickstream_v1_tickstream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedHealth.ProtoReflect.Descriptor instead.
func (*FeedHealth) Descriptor() ([]byte, []int) {
	return file_tickstream_v1_tickstream_proto_rawDescGZIP(), []int{4}
}

func (x *FeedHealth) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *FeedHealth) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *FeedHealth) GetLastTradeNs() int64 {
	if x != nil {
		return x.LastTradeNs
	}
	return 0
}

func (x *FeedHealth) GetReconnects() int64 {
	if x != nil {
		return x.Reconnects
	}
	return 0
}

func (x *FeedHealth) GetStatus() FeedStatus {
	if x != nil {
		return x.Status
	}
	return FeedStatus_FEED_STATUS_UNSPECIFIED
}

func (x *FeedHealth) GetReportedAtNs() int64 {
	if x != nil {
		return x.ReportedAtNs
	}
	return 0
}

// DeadLetter wraps an unprocessable message with the reason it was rejected.
type DeadLetter struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SourceTopic     string                 `protobuf:"bytes,1,opt,name=source_topic,json=sourceTopic,proto3" json:"source_topic,omitempty"`
	SourcePartition int32                  `protobuf:"varint,2,opt,name=source_partition,json=sourcePartition,proto3" json:"source_partition,omitempty"`
	SourceOffset    int64                  `protobuf:"varint,3,opt,name=source_offset,json=sourceOffset,proto3" json:"source_offset,omitempty"`
	Error           string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	Payload         []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	FailedAtNs      int64                  `protobuf:"varint,6,opt,name=failed_at_ns,json=failedAtNs,proto3" json:"failed_at_ns,omitempty"`
	Service         string                 `protobuf:"bytes,7,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeadLetter) Reset() {
	*x = DeadLetter{}
	mi := &file_tickstream_v1_tickstream_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeadLetter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeadLetter) ProtoMessage() {}

func (x *DeadLetter) ProtoReflect() protoreflect.Message {
	mi := &file_tickstream_v1_tickstream_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeadLetter.ProtoReflect.Descriptor instead.
func (*DeadLetter) Descriptor() ([]byte, []int) {
	return file_tickstream_v1_tickstream_proto_rawDescGZIP(), []int{5}
}

func (x *DeadLetter) GetSourceTopic() string {
	if x != nil {
		return x.SourceTopic
	}
	return ""
}

func (x *DeadLetter) GetSourcePartition() int32 {
	if x != nil {
		return x.SourcePartition
	}
	return 0
}

func (x *DeadLetter) GetSourceOffset() int64 {
	if x != nil {
		return x.SourceOffset
	}
	return 0
}

func (x *DeadLetter) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DeadLetter) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DeadLetter) GetFailedAtNs() int64 {
	if x != nil {
		return x.FailedAtNs
	}
	return 0
}

func (x *DeadLetter) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

var File_tickstream_v1_tickstream_proto protoreflect.FileDescriptor

const file_tickstream_v1_tickstream_proto_rawDesc = "" +
	"\n" +
	"\x1etickstream/v1/tickstream.proto\x12\rtickstream.v1\"\xef\x01\n" +
	"\x05Trade\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x19\n" +
	"\btrade_id\x18\x03 \x01(\tR\atradeId\x12\"\n" +
	"\revent_time_ns\x18\x04 \x01(\x03R\veventTimeNs\x12 \n" +
	"\frecv_time_ns\x18\x05 \x01(\x03R\n" +
	"recvTimeNs\x12\x14\n" +
	"\x05price\x18\x06 \x01(\tR\x05price\x12\x12\n" +
	"\x04size\x18\a \x01(\tR\x04size\x12'\n" +
	"\x04side\x18\b \x01(\x0e2\x13.tickstream.v1.SideR\x04side\"\x9c\x01\n" +
	"\rExchangeStats\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x12\n" +
	"\x04vwap\x18\x02 \x01(\tR\x04vwap\x12\x16\n" +
	"\x06volume\x18\x03 \x01(\tR\x06volume\x12\x1f\n" +
	"\vtrade_count\x18\x04 \x01(\x03R\n" +
	"tradeCount\x12\"\n" +
	"\rlast_trade_ns\x18\x05 \x01(\x03R\vlastTradeNs\"\xc9\x03\n" +
	"\aMetrics\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12&\n" +
	"\x0fwindow_start_ns\x18\x02 \x01(\x03R\rwindowStartNs\x12\"\n" +
	"\rwindow_end_ns\x18\x03 \x01(\x03R\vwindowEndNs\x12\x1f\n" +
	"\vwindow_secs\x18\x04 \x01(\x05R\n" +
	"windowSecs\x12\x12\n" +
	"\x04vwap\x18\x05 \x01(\tR\x04vwap\x12\x16\n" +
	"\x06volume\x18\x06 \x01(\tR\x06volume\x12\x1f\n" +
	"\vtrade_count\x18\a \x01(\x03R\n" +
	"tradeCount\x12!\n" +
	"\frealised_vol\x18\b \x01(\x01R\vrealisedVol\x12\x12\n" +
	"\x04high\x18\t \x01(\tR\x04high\x12\x10\n" +
	"\x03low\x18\n" +
	" \x01(\tR\x03low\x12$\n" +
	"\x0exex_spread_bps\x18\v \x01(\x01R\fxexSpreadBps\x12\"\n" +
	"\remitted_at_ns\x18\f \x01(\x03R\vemittedAtNs\x12\x1d\n" +
	"\n" +
	"last_price\x18\r \x01(\tR\tlastPrice\x12:\n" +
	"\texchanges\x18\x0e \x03(\v2\x1c.tickstream.v1.ExchangeStatsR\texchanges\"\xdb\x02\n" +
	"\x05Alert\x12\x19\n" +
	"\balert_id\x18\x01 \x01(\tR\aalertId\x12\x1b\n" +
	"\trule_name\x18\x02 \x01(\tR\bruleName\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x123\n" +
	"\bseverity\x18\x04 \x01(\x0e2\x17.tickstream.v1.SeverityR\bseverity\x12\"\n" +
	"\rwindow_end_ns\x18\x05 \x01(\x03R\vwindowEndNs\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x128\n" +
	"\x06values\x18\a \x03(\v2 .tickstream.v1.Alert.ValuesEntryR\x06values\x12\x1a\n" +
	"\bexchange\x18\b \x01(\tR\bexchange\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xdd\x01\n" +
	"\n" +
	"FeedHealth\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\"\n" +
	"\rlast_trade_ns\x18\x03 \x01(\x03R\vlastTradeNs\x12\x1e\n" +
	"\n" +
	"reconnects\x18\x04 \x01(\x03R\n" +
	"reconnects\x121\n" +
	"\x06status\x18\x05 \x01(\x0e2\x19.tickstream.v1.FeedStatusR\x06status\x12$\n" +
	"\x0ereported_at_ns\x18\x06 \x01(\x03R\freportedAtNs\"\xeb\x01\n" +
	"\n" +
	"DeadLetter\x12!\n" +
	"\fsource_topic\x18\x01 \x01(\tR\vsourceTopic\x12)\n" +
	"\x10source_partition\x18\x02 \x01(\x05R\x0fsourcePartition\x12#\n" +
	"\rsource_offset\x18\x03 \x01(\x03R\fsourceOffset\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12 \n" +
	"\ffailed_at_ns\x18\x06 \x01(\x03R\n" +
	"failedAtNs\x12\x18\n" +
	"\aservice\x18\a \x01(\tR\aservice*9\n" +
	"\x04Side\x12\x14\n" +
	"\x10SIDE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bSIDE_BUY\x10\x01\x12\r\n" +
	"\tSIDE_SELL\x10\x02*F\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04INFO\x10\x01\x12\b\n" +
	"\x04WARN\x10\x02\x12\f\n" +
	"\bCRITICAL\x10\x03*y\n" +
	"\n" +
	"FeedStatus\x12\x1b\n" +
	"\x17FEED_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15FEED_STATUS_CONNECTED\x10\x01\x12\x1c\n" +
	"\x18FEED_STATUS_RECONNECTING\x10\x02\x12\x15\n" +
	"\x11FEED_STATUS_STALE\x10\x03B7Z5github.com/anibitri/tickstream/internal/domain;domainb\x06proto3"

var (
	file_tickstream_v1_tickstream_proto_rawDescOnce sync.Once
	file_tickstream_v1_tickstream_proto_rawDescData []byte
)

func file_tickstream_v1_tickstream_proto_rawDescGZIP() []byte {
	file_tickstream_v1_tickstream_proto_rawDescOnce.Do(func() {
		file_tickstream_v1_tickstream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tickstream_v1_tickstream_proto_rawDesc), len(file_tickstream_v1_tickstream_proto_rawDesc)))
	})
	return file_tickstream_v1_tickstream_proto_rawDescData
}

var file_tickstream_v1_tickstream_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_tickstream_v1_tickstream_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_tickstream_v1_tickstream_proto_goTypes = []any{
	(Side)(0),             // 0: tickstream.v1.Side
	(Severity)(0),         // 1: tickstream.v1.Severity
	(FeedStatus)(0),       // 2: tickstream.v1.FeedStatus
	(*Trade)(nil),         // 3: tickstream.v1.Trade
	(*ExchangeStats)(nil), // 4: tickstream.v1.ExchangeStats
	(*Metrics)(nil),       // 5: tickstream.v1.Metrics
	(*Alert)(nil),         // 6: tickstream.v1.Alert
	(*FeedHealth)(nil),    // 7: tickstream.v1.FeedHealth
	(*DeadLetter)(nil),    // 8: tickstream.v1.DeadLetter
	nil,                   // 9: tickstream.v1.Alert.ValuesEntry
}
var file_tickstream_v1_tickstream_proto_depIdxs = []int32{
	0, // 0: tickstream.v1.Trade.side:type_name -> tickstream.v1.Side
	4, // 1: tickstream.v1.Metrics.exchanges:type_name -> tickstream.v1.ExchangeStats
	1, // 2: tickstream.v1.Alert.severity:type_name -> tickstream.v1.Severity
	9, // 3: tickstream.v1.Alert.values:type_name -> tickstream.v1.Alert.ValuesEntry
	2, // 4: tickstream.v1.FeedHealth.status:type_name -> tickstream.v1.FeedStatus
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_tickstream_v1_tickstream_proto_init() }
func file_tickstream_v1_tickstream_proto_init() {
	if File_tickstream_v1_tickstream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tickstream_v1_tickstream_proto_rawDesc), len(file_tickstream_v1_tickstream_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tickstream_v1_tickstream_proto_goTypes,
		DependencyIndexes: file_tickstream_v1_tickstream_proto_depIdxs,
		EnumInfos:         file_tickstream_v1_tickstream_proto_enumTypes,
		MessageInfos:      file_tickstream_v1_tickstream_proto_msgTypes,
	}.Build()
	File_tickstream_v1_tickstream_proto = out.File
	file_tickstream_v1_tickstream_proto_goTypes = nil
	file_tickstream_v1_tickstream_proto_depIdxs = nil
}
